{
 "title": "ES_Team_Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Dev ENV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "es_health_metric{server_job=\"localhost.am.co.gxo.com\"}"
    }
   ]
  },
  {
   "title": "ES Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "es_node_metric{server_job=\"localhost.am.co.gxo.com\"}"
    }
   ]
  },
  {
   "title": "Kafka Health",
   "type": "stat",
   "description": "The first node to boot in a Kafka cluster automatically becomes the controller, and there can be only one. The controller in a Kafka cluster is responsible for maintaining the list of partition leaders, and coordinating leadership transitions (in the event a partition leader becomes unavailable). If it becomes necessary to replace the controller, a new controller is randomly chosen by ZooKeeper from the pool of brokers. In general, it is not possible for this value to be greater than one, but you should definitely alert on a value of zero that lasts for more than a short period (< 1s) of time.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_health_metric{server_job=\"localhost.am.co.gxo.com\"}"
    }
   ]
  },
  {
   "title": "Kafka Dev Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_health_metric{server_job=\"localhost.am.co.gxo.com\"}"
    }
   ]
  },
  {
   "title": "Kafka Connect",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_connect_nodes_metric{server_job=\"localhost.am.co.gxo.com\"}"
    }
   ]
  },
  {
   "title": "Kafka Connect Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_nodes_metric{server_job=\"localhost.am.co.gxo.com\"}"
    }
   ]
  },
  {
   "title": "Zookeeper Connect",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "zookeeper_health_metric{server_job=\"localhost.am.co.gxo.com\"}"
    }
   ]
  },
  {
   "title": "Zookeeper Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zookeeper_health_metric{server_job=\"localhost.am.co.gxo.com\"}"
    }
   ]
  },
  {
   "title": "Kibana Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kibana_health_metric{server_job=\"localhost.am.co.gxo.com\"}"
    }
   ]
  },
  {
   "title": "Logstash Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "logstash_health_metric{server_job=\"localhost.am.co.gxo.com\"}"
    }
   ]
  },
  {
   "title": "Kafka Connect Listeners",
   "type": "table",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "kafka_connect_listeners_metric{server_job=\"localhost.am.co.gxo.com\"}"
    }
   ]
  },
  {
   "title": "Spark Jobs",
   "type": "table",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "spark_jobs_running_metrics{server_job=\"localhost.am.co.gxo.com\"}"
    }
   ]
  },
  { "title": "QA1 ENV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "QA2 ENV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "QA4 ENV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  }
 ]
}